# Generated by Django 2.0.7 on 2018-12-11 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='blog.Author')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to='blog.Author')),
            ],
        ),
    ]
