# Generated by Django 2.0.7 on 2018-12-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followers',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
