# Generated by Django 2.0.7 on 2018-12-11 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181211_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='blog.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
