# Generated by Django 2.0.7 on 2018-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181211_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='readedpost',
            field=models.ManyToManyField(blank=True, null=True, related_name='readedby', to='blog.Author'),
        ),
    ]
