# Generated by Django 2.0.7 on 2018-12-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_author_readedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='readedpost',
            field=models.ManyToManyField(blank=True, null=True, related_name='readedby', to='blog.Blog'),
        ),
    ]
