# Generated by Django 2.0.7 on 2018-12-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181211_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='readedpost',
        ),
        migrations.AddField(
            model_name='blog',
            name='readedby',
            field=models.ManyToManyField(blank=True, null=True, related_name='readed', to='blog.Author'),
        ),
    ]
